Update the SDK version of Scrypt
It's relying on posix_memalign, which is only available as of SDK
version 17 (the ndk headers say 16, but I'm told that's a bug
that'll be fixed soon).

Originally complained about by the static analyzer (and, presumably,
clang):
external/scrypt/lib/crypto/crypto_scrypt-neon.c:228:15: warning:
implicit declaration of function 'posix_memalign' is invalid in C99
[-Wimplicit-function-declaration]

Bug: None
Test: Builds on internal master without complaining about
posix_memalign being implicitly declared.

Change-Id: I5d9ecd79e0fb2372c92076bbf86e334132fb088f